describe('Authentication page', () => {
  it('Visits the Kitchen Sink', () => {
    cy.visit('https://eboutique.irigo.fr/')
    cy.wait(5000)
    cy.get('.gtm-header-login-link').click()
    cy.get('#password').click({ force: true })
    cy.scrollTo('bottom')
    cy.get('#kc-registration > .btn').click()
    cy.get('#email').type('test@test.com')
    cy.get('#firstName').type('Olga').screenshot('first-name')
    cy.get('#lastName').type('Trofimova').screenshot('last-name')
    cy.get('#password').type('BeG-123!')
    cy.get('#password-confirm').type('BeG-123!')
    cy.get('#legalAge').click()
    cy.get('.btn').should('be.visible')
    cy.get('span > a').click()
    cy.get('span > a').click()
    cy.get('#username').type('test@test.com').screenshot('username')
    cy.get('.btn').click()
    cy.get('.alert').should('be.visible').screenshot('alert')
  })
})